title: haaaaaeechan's website
author: Yuqi Pan
description: The best people in life are free！
theme: jekyll-theme-chirpy
baseurl: "/haaaaaeechan-site"  
permalink: /:categories/:year/:month/:day/:title.html
